# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish Package

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install
      - run: yarn zip

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: yarn install
      - run: yarn zip
#       - run: yarn publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Publish Package
        # You may pin to the exact commit or the version.
        # uses: TheDoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        uses: TheDoctor0/zip-release@0.6.2
        with:
          # Filename for archive
          filename: casper.zip# default is release.zip
          # Base path for archive files
          path: dist/ # optional, default is .
#           # Working directory before zipping
#           directory: # optional, default is .
#           # List of excluded files / directories
#           exclusions: # optional, default is 
#           # List of excluded files / directories with recursive wildcards (only applies on Windows with `zip` type)
#           recursive_exclusions: # optional, default is 
#           # Tool to use for archiving
#           type: # optional, default is zip
